spring.application.name=MitfahrZentraleSpringboots

# PostgreSQL Datenbank
spring.datasource.url=jdbc:postgresql://localhost:5432/mitfahrzentrale?currentSchema=public
spring.datasource.username=julius.kraemer
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate - keine automatische Tabellenerstellung, da Tabellen manuell angelegt
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Explizites Schema für Hibernate
spring.jpa.hibernate.default_schema=public

# JWT Konfiguration - mindestens 32 Zeichen!
app.jwt.secret=L1QNdQ-Bp_KB5HlIWockaJ2Y6D-SByKPs6kWFFLWrEg
app.jwt.expiration-ms=86400000
